version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

  springboot-app:
    container_name: wishlist-api
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: jeffersonacmjz/wishlist-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/wishlist
    depends_on:
      - mongodb